from io import BytesIO
from pathlib import Path

from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

from fpdf import FPDF


# Project root
BASE_DIR = Path(__file__).resolve().parents[3]

# Optional logo
LOGO_PATH = BASE_DIR / "assets" / "legalese_logo.png"


def clean_text(text: str) -> str:
    """
    Basic text cleanup.
    """

    if not text:
        return ""

    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")

    return text.strip()


# =========================================================
# TXT EXPORT
# =========================================================

def format_txt(
    text: str,
    document_type: str,
) -> bytes:
    """
    Create a TXT document.
    """

    text = clean_text(text)

    content = (
        "LEGALEASE\n"
        "AI-POWERED LEGAL DOCUMENT DRAFT\n"
        f"Document Type: {document_type}\n"
        + "=" * 70
        + "\n\n"
        + text
        + "\n\n"
        + "=" * 70
        + "\n"
        + "Generated by LegalEase.\n"
        + "AI-generated draft - professional legal review recommended.\n"
    )

    return content.encode("utf-8")


# =========================================================
# DOCX EXPORT
# =========================================================

def format_docx(
    text: str,
    document_type: str,
) -> bytes:
    """
    Create a DOCX document.
    """

    document = Document()

    # Page margins
    section = document.sections[0]

    section.top_margin = Inches(0.75)
    section.bottom_margin = Inches(0.75)
    section.left_margin = Inches(0.85)
    section.right_margin = Inches(0.85)

    # Default font
    normal_style = document.styles["Normal"]

    normal_style.font.name = "Times New Roman"
    normal_style.font.size = Pt(11)

    # -----------------------------------------------------
    # Logo
    # -----------------------------------------------------

    if LOGO_PATH.exists():

        try:

            paragraph = document.add_paragraph()

            paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

            run = paragraph.add_run()

            run.add_picture(
                str(LOGO_PATH),
                width=Inches(1.4),
            )

        except Exception:
            pass

    # -----------------------------------------------------
    # Title
    # -----------------------------------------------------

    title = document.add_paragraph()

    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    run = title.add_run("LEGALEASE")

    run.bold = True
    run.font.name = "Times New Roman"
    run.font.size = Pt(18)

    # Document type
    subtitle = document.add_paragraph()

    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

    run = subtitle.add_run(
        document_type.upper()
    )

    run.bold = True
    run.font.name = "Times New Roman"
    run.font.size = Pt(13)

    document.add_paragraph()

    # -----------------------------------------------------
    # Document content
    # -----------------------------------------------------

    text = clean_text(text)

    for line in text.split("\n"):

        line = line.strip()

        # Empty line
        if not line:

            document.add_paragraph()

            continue

        paragraph = document.add_paragraph()

        # Headings
        if line.startswith("#"):

            heading = line.lstrip("#").strip()

            run = paragraph.add_run(heading)

            run.bold = True
            run.font.name = "Times New Roman"
            run.font.size = Pt(13)

        # Bullet points
        elif line.startswith("- "):

            run = paragraph.add_run(
                "• " + line[2:]
            )

            run.font.name = "Times New Roman"
            run.font.size = Pt(11)

        else:

            run = paragraph.add_run(line)

            run.font.name = "Times New Roman"
            run.font.size = Pt(11)

    # -----------------------------------------------------
    # Footer
    # -----------------------------------------------------

    footer = section.footer

    paragraph = footer.paragraphs[0]

    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

    run = paragraph.add_run(
        "LegalEase | AI-generated legal draft | "
        "Professional review recommended"
    )

    run.font.name = "Times New Roman"
    run.font.size = Pt(8)

    # Save into memory
    output = BytesIO()

    document.save(output)

    output.seek(0)

    return output.read()


# =========================================================
# PDF CLASS
# =========================================================

class LegalEasePDF(FPDF):

    def __init__(
        self,
        document_type: str,
    ):

        super().__init__()

        self.document_type = document_type

        self.set_auto_page_break(
            auto=True,
            margin=18,
        )

    # -----------------------------------------------------
    # Header
    # -----------------------------------------------------

    def header(self):

        # Logo
        if self.page_no() == 1:

            if LOGO_PATH.exists():

                try:

                    self.image(
                        str(LOGO_PATH),
                        x=90,
                        y=8,
                        w=30,
                    )

                    self.ln(25)

                except Exception:

                    self.ln(5)

            else:

                self.ln(5)

        else:

            self.ln(5)

        # Document title
        self.set_font(
            "Times",
            "B",
            13,
        )

        self.cell(
            0,
            8,
            self.document_type.upper(),
            align="C",
        )

        self.ln(8)

    # -----------------------------------------------------
    # Footer
    # -----------------------------------------------------

    def footer(self):

        self.set_y(-15)

        self.set_font(
            "Times",
            "",
            8,
        )

        self.cell(
            0,
            8,
            f"LegalEase | Page {self.page_no()}",
            align="C",
        )


# =========================================================
# PDF EXPORT
# =========================================================

def format_pdf(
    text: str,
    document_type: str,
) -> bytes:
    """
    Create a PDF document.
    """

    pdf = LegalEasePDF(
        document_type
    )

    pdf.set_margins(
        left=18,
        top=18,
        right=18,
    )

    pdf.add_page()

    pdf.set_font(
        "Times",
        "",
        11,
    )

    text = clean_text(text)

    for line in text.split("\n"):

        line = line.strip()

        # Empty line
        if not line:

            pdf.ln(4)

            continue

        # Heading
        if line.startswith("#"):

            heading = line.lstrip("#").strip()

            pdf.set_font(
                "Times",
                "B",
                12,
            )

            pdf.multi_cell(
                0,
                7,
                heading,
            )

            pdf.set_font(
                "Times",
                "",
                11,
            )

        # Bullet
        elif line.startswith("- "):

            pdf.multi_cell(
                0,
                6,
                "• " + line[2:],
            )

        # Normal text
        else:

            pdf.multi_cell(
                0,
                6,
                line,
            )

        pdf.ln(1)

    # Generate PDF bytes
    output = pdf.output()

    if isinstance(output, str):

        return output.encode("latin-1")

    return bytes(output)